"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class control_cmd(object):
    __slots__ = ["v", "phi"]

    __typenames__ = ["double", "double"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.v = 0.0
        self.phi = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(control_cmd._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dd", self.v, self.phi))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != control_cmd._get_packed_fingerprint():
            raise ValueError("Decode error")
        return control_cmd._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = control_cmd()
        self.v, self.phi = struct.unpack(">dd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if control_cmd in parents: return 0
        tmphash = (0xe81d3db341df45a7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if control_cmd._packed_fingerprint is None:
            control_cmd._packed_fingerprint = struct.pack(">Q", control_cmd._get_hash_recursive([]))
        return control_cmd._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

